### ISSUE TITLE
udemy link not working

### ISSUE THREAD

**Issue by solagappan** [quiz-experts/HashiCorp-Certified-Terraform-Associate#1]

**Comment by quiz-experts** [comment]
Hello,

Our course is one of the highest-rated course in its section.
And that is why we have constantly been receiving threats on Linkedin and WhatsApp from a guy from Azerbaijan and forcing us to give him rights on our 100% original content. We are currently working with Udemy to help us in this cyberbullying case. 

We know this is very frustrating for our users who rely on the course. We request you to help us by allowing some time (1 or 2 days). We will deal with it and we will be back again soon.

Regards,
Quiz Experts

**Comment by quiz-experts** [comment]
Hello again,

Udemy helped us, and finally, we are online again.


Please accept our apology for the inconvenience it caused you.

We are working on a new course for HashiCorp Consul Certification and will send it to you at 100% discount as soon as we complete it as a small gift from us for your patient and trust in our course.


This group from Azerbaijan is also trying to impair our ratings by given us bad ratings from various fake accounts. Therefore we would like to personally invite you to share your experience with our Udemy course and rate us. It takes only a moment and would mean the world to us. :-)


Thanks,

Quiz Experts
Message:
